### ISSUE TITLE
Migrate from version 4 to version 6

### ISSUE THREAD

**Issue by wilav-dev** [ramiel/mongoose-sequence#142]
Is there any way of migrating from v4 to v6?

I need to use start_seq but in documentation I found this comment: An important fix about scoped counters is not backward compatible. You cannot use version 5 with scoped counters already present on your DB.

**Comment by ramiel** [comment]
Hello @wilav-dev. There's no way to migrate from version 4 to version 6 *if you have scoped counters*. Otherwise you can update with no issue. What you can do, I guess, it's try to upgrade in a controlled environment and see what happens.

If you have scoped counters, destroy the old ones keeping track of their value and recreate them. Then, manually update the value to be the same as the previous one before deletion.
