### ISSUE TITLE
.save() callback not being called when using plugin

### ISSUE THREAD

**Issue by globlee** [ramiel/mongoose-sequence#16]
The callback from the .save(callback) function of the model does not get called.

I followed the reference for the scoped usage.

No errors are seen,

using: 
"mongoose": "^4.3.4",
"mongoose-sequence": "^3.1.0",

**Comment by globlee** [comment]
Same thing without the hooks.

**Comment by globlee** [comment]
also, there is not collection for counters

**Comment by ramiel** [comment]
Can you please send the code: the schema,the plugin configuration and the code with the callback which is not called

**Comment by HugeGrenade** [comment]
This sounds like an issue I was experiencing with earlier. I was previously creating a mongodb connection via `mongoose.createConnection`. After changing it to use `mongoose.connect`, everything seems to be working find. This is probably because when you use `mongoose.createConnection` the plugin doesn't know about the Connection and the commands that the plugin uses gets buffered up. Hopefully this is the issue you were having and you only need to connect to one database.

The connection and buffer reference can be found here... https://github.com/Automattic/mongoose#connecting-to-mongodb

**Comment by globlee** [comment]
Yes that may be the issue. I am not using this software anymore and cannot test it.
