### ISSUE TITLE
Mongoose discriminator: throws [discriminator].plugin is not a function

### ISSUE THREAD

**Issue by shanmugarajbe** [ramiel/mongoose-sequence#38]
Below mongoose code with discriminator is throwing error,

` var options = { _id: false , discriminatorKey: 'studio', timestamps: {}}; `

Base Model: 
`var StudioSchema = new Schema({
  _id: { type: Number },
  cid: {  type: String, required: true }
  isActive: {type: Boolean, default: true},
}, options);
`
`var Studio = mongoose.model('Studio', StudioSchema);`

With Discriminator,
`var Shots = Studio.discriminator('shots',
                    new mongoose.Schema({
                      shots: [{
                        name: { type: String },
                        imgs: { src: String }
                      }]
                    }, options ));`

Trying to add mongoose sequence plugin as follows,
`Shots.plugin(AutoIncrement);`

It throwing error as "TypeError: Shots.plugin is not a function" 

Instead If I use `StudioSchema.plugin(AutoIncrement)`, Mongoose is throwing error as 

> document must have an _id before saving

how should I use it for discriminators?

**Comment by ramiel** [comment]
Hello. Both problems looks unrelated to this plugin to me. 

The first error says that your Shots model have no `plugin` method which is correct because plugins can only be attached to Schemas, not models.

The second error is because `_id` is mandatory in top level objects. You cannot set a schema without _id in mongo. As the mongoose documentation says here https://mongoosejs.com/docs/guide.html#_id you can pass false only for sub-documents.

Try your code without adding any plugin and you should have the same error.

**Comment by ramiel** [comment]
I close this due to inactivity
