### ISSUE TITLE
Clustered Mode

### ISSUE THREAD

**Issue by gautamverma** [ramiel/mongoose-sequence#5]
is it safe to use this in the Cluster Mode i.e. is the increment operation is atomic. I want to use however i will getting a a very high number of writes i.e. around 200-300 per second so i need to sure that this operation will be atomic and will have no conflict. I am using mongodb 3.2.x.

**Comment by ramiel** [comment]
This operation should be atomic by design. It use findAndModify the same way as is explained [here](https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/#upsert-and-unique-index). However I never tested this plugin in a cluster environment so any feedback is appreciated.

Maybe [this paragraph](https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/#sharded-collections) on the same page of the documentation says something interesting?

**Comment by gautamverma** [comment]
its works properly.

**Comment by ramiel** [comment]
Thank you!
