### ISSUE TITLE
How to do a populate?

### ISSUE THREAD

**Issue by idzer0lis** [ramiel/mongoose-sequence#66]
Hello and thanks!

I was wondering and headbanging how to do a populate query:

I am trying to use IDs for relationships...
example: a client = { name: 'Name', providers: [1,2,3,5]} 
I can save clients like that but can't retrieve them
````
const ClientSchema = new mongoose.Schema({
    name: {type: String},
    providers: [{ type: Number, ref: 'Provider' }], 
});
ClientSchema.plugin(AutoIncrement, { id: 'clientId', inc_field: 'id'}); // reference_fields ???

const ProviderSchema = new mongoose.Schema({
    name: {type: String},
});
ProviderSchema.plugin(AutoIncrement, {id: 'providerId', inc_field: 'id'});

return Promise.all([
        Client.find()
            .populate('providers') // Here
            .exec(),
        Client.count(query).exec(),
    ]).then(function (results) {
````
Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"Provider\"

Many thanks

**Comment by ramiel** [comment]
Hello. So, a couple of things here: populate works only with _id and not with id, like you're trying to do here. Also, populate should work only with objectID and not with other types.

From a larger point of view I'd suggest,in general, not to try to replace the _id of mongo collection with something else. If you need an incremental index for a collection use another field (be aware that, for mongoose, id is an alias for _id unless you specify differently). The reason is that the _id as an ObjectId is a so deep concept for mongo that trying to replace it can easily lead to issues. Also many other libraries out there rely on this concept.

The idea of having an incremental property in your model, which is also indexed, can be handy in certain situations, in fact I created this library but most of the time is just a residual of many years used to relational databases. After all it is worth remembering that ObjectIds are orderable without any new paradigm: any new objectId come before the older, when sorting descending.

**Comment by idzer0lis** [comment]
> Hello. So, a couple of things here: populate works only with _id and not with id, like you're trying to do here. Also, populate should work only with objectID and not with other types.
> 
> From a larger point of view I'd suggest,in general, not to try to replace the _id of mongo collection with something else. If you need an incremental index for a collection use another field (be aware that, for mongoose, id is an alias for _id unless you specify differently). The reason is that the _id as an ObjectId is a so deep concept for mongo that trying to replace it can easily lead to issues. Also many other libraries out there rely on this concept.
> 
> The idea of having an incremental property in your model, which is also indexed, can be handy in certain situations, in fact I created this library but most of the time is just a residual of many years used to relational databases. After all it is worth remembering that ObjectIds are orderable without any new paradigm: any new objectId come before the older, when sorting descending.

Many thanks for the detailed explanation.

I wish you a great day and thanks for the library!
Cheers
